steps:

- name: gcr.io/intern-infra/gcp-cloudbuild-gce-angular:latest
  args: [ build, -t, gcr.io/$PROJECT_ID/gcp-cloudbuild-gce-angular, . ]
  
- name: gcr.io/intern-infra/gcp-cloudbuild-gce-angular:latest
  args: [push, gcr.io/$PROJECT_ID/gcp-cloudbuild-gce-angular]


images:

- gcr.io/$PROJECT_ID/gcp-cloudbuild-gce-angular
